# -*- coding: utf-8 -*-
"""student performance predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpFdvZ9MejqIN1YR-kacEnZcdEAHWLaL

# Import libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""## Create a sample dataset"""

np.random.seed(42)
students = 200
data = pd.DataFrame({
    "Study Hours": np.random.randint(1, 10, students),
    "Attendance": np.random.randint(50, 101, students),
    "Previous Score": np.random.randint(40, 96, students),
    "Assignments Score": np.random.randint(40, 101, students)
})

data["Final Marks"] = (
    data["Study Hours"] * 2
    + data["Attendance"] * 0.2
    + data["Previous Score"] * 0.4
    + data["Assignments Score"] * 0.2
    + np.random.randint(-5, 6, students)
)

data["Final Marks"] = data["Final Marks"].clip(0, 100)
data.head()

"""# Check the data"""

print("Number of rows:", len(data))
print("\nMissing values:")
print(data.isnull().sum())
print("\nDuplicate rows:", data.duplicated().sum())

"""# Data pre-processing"""

data = data.drop_duplicates()

data = data.fillna(data.mean(numeric_only=True))

print("Data preprocessing completed.")

"""# EDA-Study hours VS Final marks"""

plt.figure(figsize=(7, 5))

plt.scatter(
    data["Study Hours"],
    data["Final Marks"]
)

plt.xlabel("Study Hours")
plt.ylabel("Final Marks")
plt.title("Study Hours vs Final Marks")

plt.show()

"""# EDA-Attendance VS Final marks"""

plt.figure(figsize=(7, 5))

plt.scatter(
    data["Attendance"],
    data["Final Marks"]
)

plt.xlabel("Attendance")
plt.ylabel("Final Marks")
plt.title("Attendance vs Final Marks")

plt.show()

"""# Distribution of marks"""

plt.figure(figsize=(7, 5))

plt.hist(data["Final Marks"], bins=10)

plt.xlabel("Final Marks")
plt.ylabel("Number of Students")
plt.title("Distribution of Final Marks")

plt.show()

"""# Select input and output"""

X = data[
    [
        "Study Hours",
        "Attendance",
        "Previous Score",
        "Assignments Score"
    ]
]

y = data["Final Marks"]

"""# Split the data"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

"""# Create the Random Forest model"""

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

"""# Make predictions"""

y_pred = model.predict(X_test)

print("Predictions completed!")

"""# Compare actual and predicted marks"""

result = pd.DataFrame({
    "Actual Marks": y_test.values,
    "Predicted Marks": y_pred
})

print(result.head(10))

"""# Evaluate the model"""

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae, 2))
print("MSE:", round(mse, 2))
print("R2 Score:", round(r2, 2))

"""# Actual vs Predicted graph"""

plt.figure(figsize=(8, 5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Marks")
plt.ylabel("Predicted Marks")
plt.title("Actual vs Predicted Marks")

plt.show()

"""# Predict marks for a new student"""

new_student = pd.DataFrame({
    "Study Hours": [7],
    "Attendance": [85],
    "Previous Score": [75],
    "Assignments Score": [80]
})

prediction = model.predict(new_student)

print("Predicted Final Marks:", round(prediction[0], 2))

"""# Save your results"""

result.to_csv(
    "student_predictions.csv",
    index=False
)

print("Results saved successfully!")